version: '3.9'

services:

  thmho-heatmap-mongodb-push:
    network_mode: "host"
    image: ragesh18/thmho-heatmap-mongodb-push:master
    container_name: thmho-heatmap-ngsi
    volumes:
      - ./entrypoint-mongodb-push.sh:/entrypoint.sh

  thmho-ros-server:
    network_mode: "host"
    image: ragesh18/thmho-heatmap-server:master
    container_name: thmho-heatmap-server
    volumes:
      - ./entrypoint-server.sh:/entrypoint.sh

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    command: mongod --port 27018
    network_mode: "host"
    ports:
      - 27018:27018
    volumes:
      - mgstorage:/data/db
      
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: flask
    network_mode: "host"
    ports:
      - 5000:5000
    depends_on:
      - mongo

  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    container_name: dash
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: dash
    network_mode: "host"
    ports:
      - 8050:8050
    depends_on:
      - flask
volumes:
  mgstorage:
    external: true